config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  
  get "log_in", to: "sessions#new"
  post "log_in", to: "sessions#create"
  delete "/log_out", to: "sessions#destroy"

  resources :user_books, path: :books
  resources :user_reviews, path: :reviews do
    resources :likes
    resources :reports
  end

  resources :genres do
    resources :genre_books, path: :books, only: [:index]
  end

  resources :authors do
    resources :author_books, path: :books, only: [:index]
  end

  scope :admin do
    # resources :authors
    resources :books
    resources :genres
    resources :reviews
    resources :users
    resources :authors
  end

  match "/404", to: "errors#file_not_found", via: :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :book_authors
  has_many :books, through: :book_authors

  validates :name, presence: true, length: { maximum: 255 }
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :book_authors
  has_many :reviews, dependent: :destroy
  has_many :authors, through: :book_authors
  has_and_belongs_to_many :genres
  has_one_attached :photo

  validates :name, presence: true, length: { maximum: 255 }
  validates :photo, content_type: {
    in: ["image/jpeg", "image/png"],
    message: "Only accept images in jpeg and png format"
  }, size: {
    less_than: 5.megabytes,
    message: "Only accept images less than 5mb"
  }
  validates :description, length: { maximum: 5000 }
end

app/models/book_author.rb
class BookAuthor < ApplicationRecord
  belongs_to :book
  belongs_to :author
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_and_belongs_to_many :books

  validates :name, :uniqueness =>  true, presence: true, length: { maximum: 255 }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :book
  has_many :review_likes, dependent: :destroy
  has_many :review_reports

  validates :content, presence: true, length: { minimum: 80, maximum: 1000 }
  validates :rating, numericality: { only_integer: true, greater_than: 0, less_than: 6 }

  scope :rv_by_book, ->(id){where book_id: id}
end

app/models/review_like.rb
class ReviewLike < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/review_report.rb
class ReviewReport < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/user.rb
require 'bcrypt'

class User < ApplicationRecord
  has_secure_password(:password)

  before_save :alter_email

  enum role: { user: 0, admin: 1 }, _prefix: :role

  validates :email, presence: true,
                    format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must be a valid email address" },
                    uniqueness: {case_sensitive: false}
  validates :password, presence: true, length: { minimum: 8, maximum: 256 }
  validates :birthday, presence: true

  validate :validate_age

  has_many :reviews, dependent: :destroy

  private

  def alter_email
    email.downcase!
  end

  def validate_age
    if birthday.present? && birthday > 13.years.ago.to_date
      errors.add(:birthday, 'should be over 13 years old to join us. Please comeback after 13.')
    end
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :is_admin?

  def index
    @authors = Author.all
    @author = Author.new
  end
  
  def create
    @author = Author.new(author_params)

    if @author.save
      redirect_to authors_path
    else
      render :index
    end
  end
  
  def update
    @author = Author.find(params[:id])
    
    if @author.update(author_params)
      redirect_to authors_path
    else
      render :index
    end
  end
  
  def destroy
    @author = Author.find(params[:id])
    @author.destroy

    redirect_to authors_path
  end

  private
  
  def author_params
    params.require(:author).permit(:name)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_admin?

  def index
    @books = Book.all
    @book = Book.new
  end
    
  def create
    @book = Book.new book_params

    if @book.save
      redirect_to books_path
    else
      flash[:danger] = "Unable to create book"
      redirect_to books_path
    end
  end

  def destroy
    BookAuthor.where(:book_id => params[:id]).destroy_all
    @book = Book.find params[:id]
    @book.destroy

    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:name, :photo, :description, author_ids: [], genre_ids: [])
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def file_not_found
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
    before_action :is_admin?
      
    def index
        @genres = Genre.all
        @genre = Genre.new
    end
        
    def create
        @genre = Genre.new(genre_params)
      
        if @genre.save
            redirect_to genres_path
        else
            render :index
        end
    end
        
    def update
        @genre = Genre.find(params[:id])
        
        if @genre.update(genre_params)
          redirect_to genres_path
        else
          render :index
        end
    end
      
    def destroy
        @genre = Genre.find(params[:id])
        @genre.destroy
    
        redirect_to genres_path
    end
    
    private
      
    def genre_params
        params.require(:genre).permit(:name)
    end
      
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :has_login?
  before_action :find_review
  before_action :find_book
  before_action :find_like, only: [:destroy]

  def create
    _user_id = session[:user_id]

    if already_liked?
      flash[:notice] = "You already liked this review."
    else
      @review.review_likes.create(user_id: _user_id)
    end 

    redirect_to user_book_path(@book)
  end

  def destroy
    if !(already_liked?)
      flash[:notice] = "Cannot unlike"
    else
      @like.destroy
    end

    redirect_to user_book_path(@book)
  end


  private

  def already_liked?
    ReviewLike.where(user_id: session[:user_id], review_id: params[:user_review_id]).exists?
  end

  def find_book
    @book = Book.find_by(id: @review[:book_id])
    if @book.nil?
      redirect_to root_path, notice: "Book does not exist."
    end
  end

  def find_review
    p params
    @review = Review.find_by(id: params[:user_review_id])
    if @review.nil?
      redirect_to root_path, notice: "Review does not exist."
    end
  end

  def find_like
    @like = @review.review_likes.find(params[:id])
    if @review.nil?
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_admin?

  def index
    @users = User.all
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to users_path
    else
      render :index
    end
  end
  
  def update
    @user = User.find(params[:id])
    
    if @user.update(user_params)
      redirect_to users_path
    else
      render :index
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_path
  end

  private
  
  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def current?(key, path)
        puts key
        puts current_page?
        puts path
        "#{key}" if current_page? path
        # We use string interpolation "#{key}" here to access the CSS classes we are going to create.
     end

    def is_admin?
        session[:user_role] == "admin"
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    if email = session[:user_email]
      @current_user ||= User.find_by email: session[:user_email]
    end
  end

  def current_user? user
    user && user == current_user
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/authors/index.html.erb
<div class="author-page">
  <h1>Authors</h1>
  <div class="header">
    <%# TODO: implement search by name %>
    <input id="txt-search-box" type="text" class="form-control" style="max-width:25rem;" placeholder="Search by author name..." title="coming soon" />
    <button id="btn-create-author" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modal-create-author">Create Author</button>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Name</th>
        <th scope="col">Created At</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @authors.each do |author| %>
        <tr>
          <th scope="row"><%= author.id %></th>
          <td><%= author.name %></td>
          <td><%= author.created_at %></td>
          <td>
            <button class="btn btn-outline-info bi-pencil-square"></button>
            <a href="<%= author_path(author) %>" data-method="delete" data-confirm="Are you sure?" role="button" class="btn btn-outline-danger bi-trash"></a>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="modal fade" id="modal-create-author" tabindex="-1">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Create author</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <%= form_with model: @author, id: "form-create-author" do |form| %>
            <div>
              <%= form.label :name, class: "form-label" %>
              <%= form.text_field :name, class: "form-control" %>
              <% @author.errors.full_messages_for(:name).each do |message| %>
                <div class="form-text"><%= message %></div>
              <% end %>
            </div>
          <% end %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button id="btn-submit-author" type="button" class="btn btn-primary">Create</button>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  function onCreateBtnClick() {
    const createAuthorForm = document.getElementById('form-create-author')
    createAuthorForm.submit()
  }

  const createAuthorBtn = document.getElementById('btn-submit-author')
  createAuthorBtn.addEventListener('click', onCreateBtnClick)

</script>

app/views/genres/index.html.erb
<div class="genre-page">
    <h1>Genres</h1>
    <div class="header">
      <%# TODO: implement search by name %>
      <input id="txt-search-box" type="text" class="form-control" style="max-width:25rem;" placeholder="Search by genre name..." title="" />
      <button id="btn-create-genre" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modal-create-genre">Create Genre</button>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Name</th>
                <th scope="col">Created At</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            <% @genres.each do |genre| %>
            <tr>
                <th scope="row"><%= genre.id %></th>
                <td><%= genre.name %></td>
                <td><%= genre.created_at %></td>
                <td>
                    <button class="btn btn-outline-info bi-pencil-square"></button>
                    <a href="<%= genre_path(genre) %>" data-method="delete" data-confirm="Are you sure?" role="button" class="btn btn-outline-danger bi-trash"></a>
                </td>
            </tr>
            <% end %>
        </tbody>
    </table>
    <div class="modal fade" id="modal-create-genre" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Create genre</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <%= form_with model: @genre, id: "form-create-genre" do |form| %>
                    <div>
                        <%= form.label :name, class: "form-label" %>
                        <%= form.text_field :name, class: "form-control" %>
                        <% @genre.errors.full_messages_for(:name).each do |message| %>
                        <div class="form-text"><%= message %></div>
                        <% end %>
                    </div>
                    <% end %>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button id="btn-submit-genre" type="button" class="btn btn-primary">Create</button>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    function onCreateBtnClick() {
      const createGenreForm = document.getElementById('form-create-genre')
      createGenreForm.submit()
    }
  
    const createGenreBtn = document.getElementById('btn-submit-genre')
    createGenreBtn.addEventListener('click', onCreateBtnClick)
</script>
  

app/views/users/index.html.erb
<div class="user-page">
  <h1>Users</h1>
  <div class="header">
    <%# TODO: implement search by name %>
    <input id="txt-search-box" type="text" class="form-control" style="max-width:25rem;" placeholder="Search by user name..." title="coming soon" />
    <%# <button id="btn-create-user" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modal-create-user">Create User</button> %>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Email</th>
        <th scope="col">Username</th>
        <th scope="col">Role</th>
        <th scope="col">Birthday</th>
        <th scope="col">Created At</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <th scope="row"><%= user.id %></th>
          <td><%= user.email %></td>
          <td><%= user.username %></td>
          <td><%= user.role %></td>
          <td><%= user.birthday %></td>
          <td><%= user.created_at %></td>
          <td>
            <button class="btn btn-outline-info bi-pencil-square"></button>
            <a href="<%= user_path(user) %>" data-method="delete" data-confirm="Are you sure?" role="button" class="btn btn-outline-danger bi-trash"></a>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%# <div class="modal fade" id="modal-create-user" tabindex="-1"> %>
  <%#   <div class="modal-dialog"> %>
  <%#     <div class="modal-content"> %>
  <%#       <div class="modal-header"> %>
  <%#         <h5 class="modal-title">Create user</h5> %>
  <%#         <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button> %>
  <%#       </div> %>
  <%#       <div class="modal-body"> %>
  <%#         <%= form_with model: @user, id: "form-create-user" do |form| %1> %>
  <%#           <div> %>
  <%#             <%= form.label :name, class: "form-label" %1> %>
  <%#             <%= form.text_field :name, class: "form-control" %1> %>
  <%#             <% @user.errors.full_messages_for(:name).each do |message| %1> %>
  <%#               <div class="form-text"><%= message %1></div> %>
  <%#             <% end %1> %>
  <%#           </div> %>
  <%#         <% end %1> %>
  <%#       </div> %>
  <%#       <div class="modal-footer"> %>
  <%#         <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button> %>
  <%#         <button id="btn-submit-user" type="button" class="btn btn-primary">Create</button> %>
  <%#       </div> %>
  <%#     </div> %>
  <%#   </div> %>
  <%# </div> %>
</div>
<script>
  function onCreateBtnClick() {
    const createUserForm = document.getElementById('form-create-user')
    createUserForm.submit()
  }

  const createUserBtn = document.getElementById('btn-submit-user')
  createUserBtn.addEventListener('click', onCreateBtnClick)

</script>