config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  
  get "log_in", to: "sessions#new"
  post "log_in", to: "sessions#create"
  delete "/log_out", to: "sessions#destroy"

  resources :user_books, path: :books
  resources :user_reviews, path: :reviews do
    resources :likes
    resources :reports
  end

  resources :genres do
    resources :genre_books, path: :books, only: [:index]
  end

  resources :authors do
    resources :author_books, path: :books, only: [:index]
  end

  scope :admin do
    # resources :authors
    resources :books
    resources :genres
    resources :reviews
    resources :users
    resources :authors
  end

  match "/404", to: "errors#file_not_found", via: :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :book_authors
  has_many :books, through: :book_authors

  validates :name, presence: true, length: { maximum: 255 }
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :book_authors
  has_many :reviews, dependent: :destroy
  has_many :authors, through: :book_authors
  has_and_belongs_to_many :genres
  has_one_attached :photo

  validates :name, presence: true, length: { maximum: 255 }
  validates :photo, content_type: {
    in: ["image/jpeg", "image/png"],
    message: "Only accept images in jpeg and png format"
  }, size: {
    less_than: 5.megabytes,
    message: "Only accept images less than 5mb"
  }
  validates :description, length: { maximum: 5000 }
end

app/models/book_author.rb
class BookAuthor < ApplicationRecord
  belongs_to :book
  belongs_to :author
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_and_belongs_to_many :books

  validates :name, :uniqueness =>  true, presence: true, length: { maximum: 255 }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :book
  has_many :review_likes, dependent: :destroy
  has_many :review_reports

  validates :content, presence: true, length: { minimum: 80, maximum: 1000 }
  validates :rating, numericality: { only_integer: true, greater_than: 0, less_than: 6 }

  scope :rv_by_book, ->(id){where book_id: id}
end

app/models/review_like.rb
class ReviewLike < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/review_report.rb
class ReviewReport < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/user.rb
require 'bcrypt'

class User < ApplicationRecord
  has_secure_password(:password)

  before_save :alter_email

  enum role: { user: 0, admin: 1 }, _prefix: :role

  validates :email, presence: true,
                    format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must be a valid email address" },
                    uniqueness: {case_sensitive: false}
  validates :password, presence: true, length: { minimum: 8, maximum: 256 }
  validates :birthday, presence: true

  validate :validate_age

  has_many :reviews, dependent: :destroy

  private

  def alter_email
    email.downcase!
  end

  def validate_age
    if birthday.present? && birthday > 13.years.ago.to_date
      errors.add(:birthday, 'should be over 13 years old to join us. Please comeback after 13.')
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_admin?

  def index
    @books = Book.all
    @book = Book.new
  end
    
  def create
    @book = Book.new book_params

    if @book.save
      redirect_to books_path
    else
      flash[:danger] = "Unable to create book"
      redirect_to books_path
    end
  end

  def destroy
    BookAuthor.where(:book_id => params[:id]).destroy_all
    @book = Book.find params[:id]
    @book.destroy

    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:name, :photo, :description, author_ids: [], genre_ids: [])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :has_login?
  before_action :find_review
  before_action :find_book
  before_action :find_like, only: [:destroy]

  def create
    _user_id = session[:user_id]

    if already_liked?
      flash[:notice] = "You already liked this review."
    else
      @review.review_likes.create(user_id: _user_id)
    end 

    redirect_to user_book_path(@book)
  end

  def destroy
    if !(already_liked?)
      flash[:notice] = "Cannot unlike"
    else
      @like.destroy
    end

    redirect_to user_book_path(@book)
  end


  private

  def already_liked?
    ReviewLike.where(user_id: session[:user_id], review_id: params[:user_review_id]).exists?
  end

  def find_book
    @book = Book.find_by(id: @review[:book_id])
    if @book.nil?
      redirect_to root_path, notice: "Book does not exist."
    end
  end

  def find_review
    p params
    @review = Review.find_by(id: params[:user_review_id])
    if @review.nil?
      redirect_to root_path, notice: "Review does not exist."
    end
  end

  def find_like
    @like = @review.review_likes.find(params[:id])
    if @review.nil?
      redirect_to root_path
    end
  end
end

app/controllers/user_reviews_controller.rb
class UserReviewsController < ApplicationController
  def create
    @review = Review.new review_params
    @book = Book.find_by id: @review[:book_id]
    
    p @review
    if @review.save
      redirect_to user_book_path(@book)
    else
      @reviews = Review.rv_by_book @book.id
      render "user_books/show"
    end
  end

  private 

  def review_params
    params.require(:review).permit(:content, :rating, :book_id, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_admin?

  def index
    @users = User.all
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to users_path
    else
      render :index
    end
  end
  
  def update
    @user = User.find(params[:id])
    
    if @user.update(user_params)
      redirect_to users_path
    else
      render :index
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_path
  end

  private
  
  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def current?(key, path)
        puts key
        puts current_page?
        puts path
        "#{key}" if current_page? path
        # We use string interpolation "#{key}" here to access the CSS classes we are going to create.
     end

    def is_admin?
        session[:user_role] == "admin"
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    if email = session[:user_email]
      @current_user ||= User.find_by email: session[:user_email]
    end
  end

  def current_user? user
    user && user == current_user
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/user_reviews/_form.html.erb
<%= form_for @review, :url => user_reviews_path do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :book_id, value: @book.id %>

  <div>
    <%= f.label :rating %>
    <div class="box box-orange box-example-1to10">
      <div class="box-body">
          <%= f.select :rating, (1..5), {}, { id: "example-1to10" } %>
      </div>
    </div>
  </div>

  <div>
    <%= f.label :content %>
    <%= f.text_area :content, placeholder: "Create review", class: "form-control mt-1", id: "content-input" %>
  </div>

  <div class="d-grid gap-2 mt-3">
    <%= f.submit "Post", class: "btn btn-focus", id: "submit-rv-btn" %>
  </div>
<% end %>

<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-bar-rating/1.2.2/jquery.barrating.min.js"></script>

<style>
  .br-widget {
    display: flex;
    align-items: center;
  }  

  .box-body {
    border: none !important;
    padding-top: 0 !important;
    height: 45px !important;
  }

  .box-example-1to10 .br-wrapper {
    margin: 0 !important;
    left: initial !important;
  }

  .box {
    margin-top: 0 !important;
  }
</style>

<script>
  $(function() {
    function ratingEnable() {
      $('#example-1to10').barrating('show', {
        theme: 'bars-1to10'
      });
    }

    ratingEnable();
  });

  if($('#content-input').val() ==  "") 
    $('#submit-rv-btn').attr('disabled', true);

  $('#content-input').keyup(function(){
    if($('#content-input').val() !=  "") 
        $('#submit-rv-btn').attr('disabled', false);    
    else
        $('#submit-rv-btn').attr('disabled', true);   
  });
</script>

app/views/user_reviews/_review.html.erb
<li class="user-review d-flex my-4">
  <div class="user-review--avatar me-3">
    <%= image_tag "user.png" %>
  </div>
  <div class="user-review--user">
    <div class="highlight-text">
      <%= review.user.username %>
    </div>
    <p>rated it <%= review.rating %></p>
    <p>
      <%= review.content %>
    </p>
    <div class="d-flex">
      <div class="mr-2">
        <% pre_like = review.review_likes.find { |like| like.user_id == session[:user_id] } %>
        <% if pre_like %>
          <%= link_to 'Unlike', user_review_like_path(review, pre_like), method: :delete %>
        <% else %>
          <%= link_to 'Like', user_review_likes_path(review), method: :post %>
        <% end %>
      </div>
      <div>
        <a class="link-danger" data-bs-toggle="modal" data-bs-target="#modal-create-report">Report</a>
      </div>
      <div>
        <div class="modal fade" id="modal-create-report" tabindex="-1">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title">Report this review</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <%= form_for :report, :url => user_review_reports_path(review, :report), :html => { :id => "form-create-report" } do |f| %>
                  <%= f.label :description, class: "form-label" %>
                  <%= f.text_field :description, class: "form-control" %>
                <% end %>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button id="btn-submit-report" type="button" class="btn btn-primary">Create</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</li>
<script>
  function onCreateBtnClick() {
    const createReportForm = document.getElementById('form-create-report')
    createReportForm.submit()
  }

  const createReportBtn = document.getElementById('btn-submit-report')
  createReportBtn.addEventListener('click', onCreateBtnClick)
</script>