config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  
  get "log_in", to: "sessions#new"
  post "log_in", to: "sessions#create"
  delete "/log_out", to: "sessions#destroy"

  resources :user_books, path: :books
  resources :user_reviews, path: :reviews do
    resources :likes
    resources :reports
  end

  resources :genres do
    resources :genre_books, path: :books, only: [:index]
  end

  resources :authors do
    resources :author_books, path: :books, only: [:index]
  end

  scope :admin do
    # resources :authors
    resources :books
    resources :genres
    resources :reviews
    resources :users
    resources :authors
  end

  match "/404", to: "errors#file_not_found", via: :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :book_authors
  has_many :books, through: :book_authors

  validates :name, presence: true, length: { maximum: 255 }
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :book_authors
  has_many :reviews, dependent: :destroy
  has_many :authors, through: :book_authors
  has_and_belongs_to_many :genres
  has_one_attached :photo

  validates :name, presence: true, length: { maximum: 255 }
  validates :photo, content_type: {
    in: ["image/jpeg", "image/png"],
    message: "Only accept images in jpeg and png format"
  }, size: {
    less_than: 5.megabytes,
    message: "Only accept images less than 5mb"
  }
  validates :description, length: { maximum: 5000 }
end

app/models/book_author.rb
class BookAuthor < ApplicationRecord
  belongs_to :book
  belongs_to :author
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_and_belongs_to_many :books

  validates :name, :uniqueness =>  true, presence: true, length: { maximum: 255 }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :book
  has_many :review_likes, dependent: :destroy
  has_many :review_reports

  validates :content, presence: true, length: { minimum: 80, maximum: 1000 }
  validates :rating, numericality: { only_integer: true, greater_than: 0, less_than: 6 }

  scope :rv_by_book, ->(id){where book_id: id}
end

app/models/review_like.rb
class ReviewLike < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/review_report.rb
class ReviewReport < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/user.rb
require 'bcrypt'

class User < ApplicationRecord
  has_secure_password(:password)

  before_save :alter_email

  enum role: { user: 0, admin: 1 }, _prefix: :role

  validates :email, presence: true,
                    format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must be a valid email address" },
                    uniqueness: {case_sensitive: false}
  validates :password, presence: true, length: { minimum: 8, maximum: 256 }
  validates :birthday, presence: true

  validate :validate_age

  has_many :reviews, dependent: :destroy

  private

  def alter_email
    email.downcase!
  end

  def validate_age
    if birthday.present? && birthday > 13.years.ago.to_date
      errors.add(:birthday, 'should be over 13 years old to join us. Please comeback after 13.')
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_admin?

  def index
    @books = Book.all
    @book = Book.new
  end
    
  def create
    @book = Book.new book_params

    if @book.save
      redirect_to books_path
    else
      flash[:danger] = "Unable to create book"
      redirect_to books_path
    end
  end

  def destroy
    BookAuthor.where(:book_id => params[:id]).destroy_all
    @book = Book.find params[:id]
    @book.destroy

    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:name, :photo, :description, author_ids: [], genre_ids: [])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :has_login?
  before_action :find_review
  before_action :find_book
  before_action :find_like, only: [:destroy]

  def create
    _user_id = session[:user_id]

    if already_liked?
      flash[:notice] = "You already liked this review."
    else
      @review.review_likes.create(user_id: _user_id)
    end 

    redirect_to user_book_path(@book)
  end

  def destroy
    if !(already_liked?)
      flash[:notice] = "Cannot unlike"
    else
      @like.destroy
    end

    redirect_to user_book_path(@book)
  end


  private

  def already_liked?
    ReviewLike.where(user_id: session[:user_id], review_id: params[:user_review_id]).exists?
  end

  def find_book
    @book = Book.find_by(id: @review[:book_id])
    if @book.nil?
      redirect_to root_path, notice: "Book does not exist."
    end
  end

  def find_review
    p params
    @review = Review.find_by(id: params[:user_review_id])
    if @review.nil?
      redirect_to root_path, notice: "Review does not exist."
    end
  end

  def find_like
    @like = @review.review_likes.find(params[:id])
    if @review.nil?
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_admin?

  def index
    @users = User.all
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to users_path
    else
      render :index
    end
  end
  
  def update
    @user = User.find(params[:id])
    
    if @user.update(user_params)
      redirect_to users_path
    else
      render :index
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_path
  end

  private
  
  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def current?(key, path)
        puts key
        puts current_page?
        puts path
        "#{key}" if current_page? path
        # We use string interpolation "#{key}" here to access the CSS classes we are going to create.
     end

    def is_admin?
        session[:user_role] == "admin"
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    if email = session[:user_email]
      @current_user ||= User.find_by email: session[:user_email]
    end
  end

  def current_user? user
    user && user == current_user
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light px-4">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand d-flex" do %>
      <section class="brand brand--focus">Amazing</section><section class="brand">GudRead</section>
    <% end %>

    <form class="d-flex ms-4">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-primary" type="submit">Search</button>
    </form>

    <ul class="navbar-nav mb-2 mb-lg-0 ms-auto">
      <%if logged_in? && is_admin? %>
        <li class="nav-item d-flex align-items-center mx-4">
          <%= link_to "Admin", books_path, class: "text-dark" %>
        </li>
      <% end %>

      <% if logged_in?  %>
        <li class="nav-item dropdown ms-4">
          <%= link_to "Hello, #{current_user.username}", "#", class: "nav-link dropdown-toggle", id: "navbarDropdown", role:"button", "data-bs-toggle": "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-lg-end">
            <li class="dropdown-item"><%= link_to "Profile", "#" %></li>
            <li class="dropdown-item"><%= link_to "Change password", "#" %></li>
            <li><hr class="dropdown-divider"></li>
            <li class="dropdown-item"><%= link_to "Logout", log_out_path, method: :delete, class: "text-danger" %></li>
          </ul>
        </li>
        <% else  %>
        <li class="nav-item d-flex align-items-center mx-4">
          <%= link_to "Login", log_in_path, class: "text-dark" %>
        </li>
        <li class="nav-item">
          <button type="button" class="btn btn-primary px-4">
            <%= link_to "Sign Up", sign_up_path, class: "text-white" %>
          </button>
        </li>
      <% end  %>
    </ul>
  </div>
</nav>

app/views/layouts/_sidebar_menu.html.erb
<nav class="navbar sidebar navbar-light bg-light">
<div class="logo">
        <%= link_to root_path, class: "navbar-brand d-flex" do %>
        <section class="brand brand--focus">Amazing</section><section class="brand">GudRead</section>
        <% end %>
</div>
<div class="menu">
        <ul>
                <li>
                        <i class="bi bi-people"></i><%= link_to "Users", "/admin/users"%>
                </li>
                <li>
                        <i class="bi bi-book"></i><%= link_to "Books", "/admin/books"%>
                </li>
                <li>
                        <i class="bi bi-star"></i><%= link_to "Reviews", "/admin/reviews"%>
                </li>
                <li><i class="bi bi-exclamation-octagon"></i><%= link_to "Reports", "#" %></li>
                <li><i class="bi bi-person-circle"></i><%= link_to "Authors", "/admin/authors" %></li>
                <li><i class="bi bi-collection-play"></i><%= link_to "Genres", "/admin/genres" %></li>
        </ul>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AmazingGudRead</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="app">
      <% if request.fullpath !~ %r[^/admin] %>
        <%# show header for user's routes %>
        <%= render "layouts/header" %>
        <div class="container-fluid">
          <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>">
              <%= message %>
            </div>
          <% end %>
          <%= yield %>
        </div>
      <% else%>
      <div class="d-flex">
        <%= render "layouts/sidebar_menu"%>
          <div class="container-fluid">
            <% flash.each do |message_type, message| %>
              <div class="alert alert-<%= message_type %>">
                <%= message %>
              </div>
            <% end %>
            <%= yield %>
          </div>
        <% end %>
      </div>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= pluralize object.errors.count, "error(s)" %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>